[package]
name = "jsi-tests"
version = "0.3.1-alpha.1"
edition = "2021"
links = "hermes"
publish = false

[dependencies]
cxx = "1.0"
anyhow = "1.0"
jsi-sys = { path = "../jsi-sys" }
jsi = { path = "../jsi" }

[build-dependencies]
cxx-build = "1.0"
dunce = "1.0"
